### ISSUE TITLE
CI 관련 질문

### ISSUE THREAD

**Issue by ldh019** [boostcampwm-2022/android01-UCMC#19]
1. yml 파일에 보니까 자바 버전이 11로 되어있는데, 일치하지 않아도 괜찮은건가요?
2. 아까 저희 google.service 파일 app에서 찾아서 안된다고 그랬는데, yml 파일에서 app 폴더에서 찾는데 혹시 저거 때문은 아닐까요?

**Comment by Hyunji99Choi** [comment]
👀❗

**Comment by minseonglove** [comment]
1. 고치는걸 까먹었네요 헤헤 다운그레이드가 아니라 괜찮아뵈긴 하지만 그래도 버전이랑 맞출게요
2. `echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json`이 부분은 app안에 google-services.json를 새로만들어서 secrets.GOOGLE_SERVICES_JSON에 있는 내용물을 넣어주는 부분이라 요것이랑은 관계 없읍니다
